### ISSUE TITLE
Panic: runtime error for /oauth/logout

### ISSUE THREAD

**Issue by jangaraj** [gambol99/keycloak-proxy#253]
I'm testing keycloak proxy with Google OAuth. My config:
```
discovery-url: https://accounts.google.com/.well-known/openid-configuration
client-id: <CLIENT_ID>
client-secret: <CLIENT_SECRET>
listen: 0.0.0.0:2016
secure-cookie: false
enable-logging: true
enable-metrics: true
upstream-keepalives: true
redirection-url: <URL>
upstream-url: http://localhost:8081/
resources:
- uri: /*
  methods:
  - GET
```

I see this runtime error, when I try to logout `/oauth/logout` (no `redirect` parameter):
```
Panic: runtime error: invalid memory address or nil pointer dereference
goroutine 46 [running]:
runtime/debug.Stack(0x48, 0x0, 0x0)
        /usr/local/go/src/runtime/debug/stack.go:24 +0x79
runtime/debug.PrintStack()
        /usr/local/go/src/runtime/debug/stack.go:16 +0x22
github.com/gambol99/keycloak-proxy/vendor/github.com/pressly/chi/middleware.Recoverer.func1.1(0xc42023bc00, 0xc73ae0, 0xc4204768c0)
        /go/src/github.com/gambol99/keycloak-proxy/vendor/github.com/pressly/chi/middleware/recoverer.go:28 +0x1c0
panic(0x937a00, 0xc9cf90)
        /usr/local/go/src/runtime/panic.go:489 +0x2cf
net/url.(*URL).String(0x0, 0xc42023be00, 0x7f68ce504e28)
        /usr/local/go/src/net/url/url.go:726 +0x40
main.(*oauthProxy).logoutHandler(0xc420079c00, 0x7f68ce504e28, 0xc4204c3440, 0xc42023be00)
        /go/src/github.com/gambol99/keycloak-proxy/handlers.go:298 +0x182
main.(*oauthProxy).(main.logoutHandler)-fm(0x7f68ce504e28, 0xc4204c3440, 0xc42023be00)
        /go/src/github.com/gambol99/keycloak-proxy/server.go:193 +0x48
net/http.HandlerFunc.ServeHTTP(0xc4203cbcd0, 0x7f68ce504e28, 0xc4204c3440, 0xc42023be00)
        /usr/local/go/src/net/http/server.go:1942 +0x44
github.com/gambol99/keycloak-proxy/vendor/github.com/pressly/chi.(*Mux).routeHTTP(0xc42003e150, 0x7f68ce504e28, 0xc4204c3440, 0xc42023be00)
        /go/src/github.com/gambol99/keycloak-proxy/vendor/github.com/pressly/chi/mux.go:414 +0x262
github.com/gambol99/keycloak-proxy/vendor/github.com/pressly/chi.(*Mux).(github.com/gambol99/keycloak-proxy/vendor/github.com/pressly/chi.routeHTTP)-fm(0x7f68ce504e28, 0xc4204c3440, 0xc42023be00)
        /go/src/github.com/gambol99/keycloak-proxy/vendor/github.com/pressly/chi/mux.go:349 +0x48
net/http.HandlerFunc.ServeHTTP(0xc4203cbc70, 0x7f68ce504e28, 0xc4204c3440, 0xc42023be00)
        /usr/local/go/src/net/http/server.go:1942 +0x44
github.com/gambol99/keycloak-proxy/vendor/github.com/pressly/chi.(*Mux).ServeHTTP(0xc42003e150, 0x7f68ce504e28, 0xc4204c3440, 0xc42023be00)
        /go/src/github.com/gambol99/keycloak-proxy/vendor/github.com/pressly/chi/mux.go:69 +0x2b6
github.com/gambol99/keycloak-proxy/vendor/github.com/pressly/chi.(*Mux).Mount.func1(0x7f68ce504e28, 0xc4204c3440, 0xc42023be00)
        /go/src/github.com/gambol99/keycloak-proxy/vendor/github.com/pressly/chi/mux.go:297 +0x1bb
net/http.HandlerFunc.ServeHTTP(0xc42013eba0, 0x7f68ce504e28, 0xc4204c3440, 0xc42023be00)
        /usr/local/go/src/net/http/server.go:1942 +0x44
main.proxyDenyMiddleware.func1(0x7f68ce504e28, 0xc4204c3440, 0xc42023bd00)
        /go/src/github.com/gambol99/keycloak-proxy/middleware.go:390 +0x1ef
net/http.HandlerFunc.ServeHTTP(0xc42013ec60, 0x7f68ce504e28, 0xc4204c3440, 0xc42023bd00)
        /usr/local/go/src/net/http/server.go:1942 +0x44
github.com/gambol99/keycloak-proxy/vendor/github.com/pressly/chi.(*ChainHandler).ServeHTTP(0xc42003cec0, 0x7f68ce504e28, 0xc4204c3440, 0xc42023bd00)
        /go/src/github.com/gambol99/keycloak-proxy/vendor/github.com/pressly/chi/chain.go:29 +0x52
github.com/gambol99/keycloak-proxy/vendor/github.com/pressly/chi.(*Mux).routeHTTP(0xc42003e000, 0x7f68ce504e28, 0xc4204c3440, 0xc42023bd00)
        /go/src/github.com/gambol99/keycloak-proxy/vendor/github.com/pressly/chi/mux.go:414 +0x262
github.com/gambol99/keycloak-proxy/vendor/github.com/pressly/chi.(*Mux).(github.com/gambol99/keycloak-proxy/vendor/github.com/pressly/chi.routeHTTP)-fm(0x7f68ce504e28, 0xc4204c3440, 0xc42023bd00)
        /go/src/github.com/gambol99/keycloak-proxy/vendor/github.com/pressly/chi/mux.go:349 +0x48
net/http.HandlerFunc.ServeHTTP(0xc4203cbb90, 0x7f68ce504e28, 0xc4204c3440, 0xc42023bd00)
        /usr/local/go/src/net/http/server.go:1942 +0x44
main.(*oauthProxy).proxyMiddleware.func1(0x7f68ce504e28, 0xc4204c3440, 0xc42023bd00)
        /go/src/github.com/gambol99/keycloak-proxy/forwarding.go:31 +0x74
net/http.HandlerFunc.ServeHTTP(0xc42013e7e0, 0x7f68ce504e28, 0xc4204c3440, 0xc42023bd00)
        /usr/local/go/src/net/http/server.go:1942 +0x44
main.(*oauthProxy).metricsMiddleware.func1(0x7f68ce504e28, 0xc4204c3440, 0xc42023bd00)
        /go/src/github.com/gambol99/keycloak-proxy/middleware.go:98 +0x1d7
net/http.HandlerFunc.ServeHTTP(0xc42013e920, 0x7f68ce504e28, 0xc4204c3440, 0xc42023bd00)
        /usr/local/go/src/net/http/server.go:1942 +0x44
main.(*oauthProxy).loggingMiddleware.func1(0x7f68ce504e28, 0xc4204c3440, 0xc42023bd00)
        /go/src/github.com/gambol99/keycloak-proxy/middleware.go:69 +0x10a
net/http.HandlerFunc.ServeHTTP(0xc42013e940, 0x7f68ce504e28, 0xc4204c3440, 0xc42023bd00)
        /usr/local/go/src/net/http/server.go:1942 +0x44
main.entrypointMiddleware.func1(0xc73ae0, 0xc4204768c0, 0xc42023bc00)
        /go/src/github.com/gambol99/keycloak-proxy/middleware.go:55 +0x299
net/http.HandlerFunc.ServeHTTP(0xc42013e960, 0xc73ae0, 0xc4204768c0, 0xc42023bc00)
        /usr/local/go/src/net/http/server.go:1942 +0x44
github.com/gambol99/keycloak-proxy/vendor/github.com/pressly/chi/middleware.Recoverer.func1(0xc73ae0, 0xc4204768c0, 0xc42023bc00)
        /go/src/github.com/gambol99/keycloak-proxy/vendor/github.com/pressly/chi/middleware/recoverer.go:35 +0x9f
net/http.HandlerFunc.ServeHTTP(0xc42013e980, 0xc73ae0, 0xc4204768c0, 0xc42023bc00)
        /usr/local/go/src/net/http/server.go:1942 +0x44
github.com/gambol99/keycloak-proxy/vendor/github.com/pressly/chi.(*Mux).ServeHTTP(0xc42003e000, 0xc73ae0, 0xc4204768c0, 0xc42023bb00)
        /go/src/github.com/gambol99/keycloak-proxy/vendor/github.com/pressly/chi/mux.go:80 +0x1d8
net/http.serverHandler.ServeHTTP(0xc420067340, 0xc73ae0, 0xc4204768c0, 0xc42023bb00)
        /usr/local/go/src/net/http/server.go:2568 +0x92
net/http.(*conn).serve(0xc4204ce000, 0xc747a0, 0xc4204c20c0)
        /usr/local/go/src/net/http/server.go:1825 +0x612
created by net/http.(*Server).Serve
        /usr/local/go/src/net/http/server.go:2668 +0x2ce
```

**Comment by gambol99** [comment]
fixed in #254
